### ISSUE TITLE
Create Users

### ISSUE THREAD

**Issue by smarbos** [adopteitor/adopteitor-api#10]
Create Users
- [x] Model
- [x] Collection
- [x] Service
- [x] something more?

**Comment by smarbos** [comment]
Should this be the Human model instead of User?

**Comment by anabellaspinelli** [comment]
@smarbos do we need a way to differentiate between admin users and "visitor" users?

If so, it could be:
```
human => visitor with an account
user => admin
```

**Comment by smarbos** [comment]
Maybe "user" and "admin" could be roles of the Human entity.
To make it simpler. And only humans with role Admin can access the admin panel and use protected endpoints.

**Comment by anabellaspinelli** [comment]
Yes, that that. Only authenticated admins get do break stuff.

**Comment by smarbos** [comment]
I'm adding 
```
role: {
    type: String,
    required: true,
    enum: ['User', 'Admin']
  }
```

To the Human schema and closing this issue.
