### ISSUE TITLE
About Animal Schema

### ISSUE THREAD

**Issue by smarbos** [adopteitor/adopteitor-api#12]
```
const AnimalSchema = new Schema({
  stage: { / SHouldn't this be autocalculated based on the dateOfBirth?
    type: String,
    required: true
  },
  name: { // Should be displayName?
    type: String,
    required: true
  },
  dateOfBirth: {
    type: Date,
    required: true
  },
  description: { // A description of the animal.
    type: String,
    required: true
  },
  sex: {
    type: String,
    required: true
  },
  location: { // A string describing where in the world the animal is located
    type: String,
    required: false
  },
  entryDate: {
    type: Date,
    required: true
  }
  state: { // Adopted, in adoption, other?
    type: String,
    required: true
  }
});
```

- I added a **state** field to indicate if the animal is in adoption, adopted or any other condition.
- I wondered if the **stage** field should automatic generated based on the dateOfBirth and a "threshold setting" for the "stages"?
- Also, how can we handle different species? Maybe a shelter could have dogs and cats, and show them separately? I think this could be a common scenario.
- I added **location** field because right now in Adopta un Galgo en Argentina, we have Galguitos in Buenos Aires and Rosario City.

**Comment by anabellaspinelli** [comment]
@smarbos I hadn't seen this!

- I'm changing `state` to `status` so that it's easier not to confuse it with `stage`.
- Now that I understand what `stage` is about, is it something like `["puppy", "adult",  "oldie"]`? 
  - I would have it as a list of allowed valued for now (like `sex` is either female or male) and then we can think about adding a way for it to be calculated based on "thresholds".
    - About the "thresholds", do you think they should be user-defined?
- About different species (or races?) I would add that as a free text field in the `Animal` and then we can think about allowing the user to define them (similar to `stage`).

**Comment by smarbos** [comment]
- Status is ok.
- Stage is just that, ["puppy", "adult", "oldie"].
- I like the idea of having the thresholds as user-defined values for each stage.
- First of all, specie and race are different things and I think we should specify both of them. Im not sure, maybe we need another service to handle the species and/or races, and we can then link these properties to the animals. (animal.specie will be the ID of the specie) So we can keep these things separated.
You have to first define a Specie and a Race to start adding animals?

**Comment by smarbos** [comment]
Also @anabellaspinelli  you say that you are changing "state" to "status" are you working on that?
Because I'm working on the animal-model and I could implement these changes, let me know!

This is the current animalSchema:

```
{
    stage: {
      type: String,
      required: true,
      enum: ['Puppy', 'Adult', 'Oldie']
    },
    name: {
      type: String,
      required: true
    },
    dateOfBirth: {
      type: Date,
      required: true
    },
    description: {
      type: String,
      required: true
    },
    sex: {
      type: String,
      required: true
      enum: ['Male', 'Female', 'Other']
    },
    location: {
      type: String,
      required: false
    },
    entryDate: {
      type: Date,
      required: true
    },
    status: {
      type: String,
      required: true,
      enum: ['Adopted', 'Other']
    },
    specie: {
      type: Schema.Types.ObjectId,
      required: true
    },
    race: {
      type: Schema.Types.ObjectId,
      required: false
    },
    photos: [{
      type: String,
      required: false
    }]
  }
```

**Comment by smarbos** [comment]
Animal schema updated: #6ab275c240810cd60e0832008791456d970bc33a
