### ISSUE TITLE
Mongo connection failure on test run

### ISSUE THREAD

**Issue by anabellaspinelli** [adopteitor/adopteitor-api#19]
Do you think we should maybe tell the app to not try to connect to the DB when only it's running tests via some config option? 

Also for error logging like in 404 tests like this:
```
    404
error: Page not found {"type":"FeathersError","name":"NotFound","code":404,"className":"not-found","data":{"url":"/path/to/nowhere"},"errors":{}}

      ✓ shows a 404 HTML page
```

Or do we plan to test DB connection? In that case we could dockerize it too 🐳 

WDYT @smarbos @josx ?

**Comment by josx** [comment]
I think that maybe we want to use db connection on tests (at least in more complex integration tests).
But we can use memory (on feathers) instead of mongo, an config this on config/test.conf

**Comment by anabellaspinelli** [comment]
Cool 🆒 

I've disabled the error logging on tests, so I'm closing this, at least for now.
